apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovh-dns-updater
  labels:
    app: ovh-dns-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ovh-dns-updater
  template:
    metadata:
      labels:
        app: ovh-dns-updater
    spec:
      containers:
      - name: ovh-dns-updater
        image: ghcr.io/mangelajo/ovh-dns-updater:main
        imagePullPolicy: Always
        env:
        - name: OVH_APPLICATION_KEY
          valueFrom:
            secretKeyRef:
              name: ovh-dns-updater-secret
              key: OVH_APPLICATION_KEY
        - name: OVH_APPLICATION_SECRET
          valueFrom:
            secretKeyRef:
              name: ovh-dns-updater-secret
              key: OVH_APPLICATION_SECRET
        - name: OVH_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: ovh-dns-updater-secret
              key: OVH_CONSUMER_KEY
        - name: OVH_ENDPOINT
          value: "ovh-eu"
        - name: DNS_ZONE
          valueFrom:
            configMapKeyRef:
              name: ovh-dns-updater-config
              key: DNS_ZONE
        - name: DNS_RECORD
          valueFrom:
            configMapKeyRef:
              name: ovh-dns-updater-config
              key: DNS_RECORD
              optional: true
        - name: CHECK_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: ovh-dns-updater-config
              key: CHECK_INTERVAL
              optional: true
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi