apiVersion: v1
kind: Secret
metadata:
  name: ovh-dns-updater-secret
type: Opaque
data:
  OVH_APPLICATION_KEY: ${OVH_APPLICATION_KEY}
  OVH_APPLICATION_SECRET: ${OVH_APPLICATION_SECRET}
  OVH_CONSUMER_KEY: ${OVH_CONSUMER_KEY}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovh-dns-updater-config
data:
  domains.yaml: |
    domains:
      - zone: ${DNS_ZONE}
        records:
          - ${DNS_RECORD}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovh-dns-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ovh-dns-updater
  template:
    metadata:
      labels:
        app: ovh-dns-updater
    spec:
      containers:
      - name: ovh-dns-updater
        image: ghcr.io/mangelajo/ovh-dns-updater:latest
        env:
        - name: CHECK_INTERVAL
          value: "5m"
        - name: DOMAINS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: ovh-dns-updater-config
              key: domains.yaml
        - name: OVH_APPLICATION_KEY
          valueFrom:
            secretKeyRef:
              name: ovh-dns-updater-secret
              key: OVH_APPLICATION_KEY
        - name: OVH_APPLICATION_SECRET
          valueFrom:
            secretKeyRef:
              name: ovh-dns-updater-secret
              key: OVH_APPLICATION_SECRET
        - name: OVH_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: ovh-dns-updater-secret
              key: OVH_CONSUMER_KEY