apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ovh-dns-updater.fullname" . }}-config
  labels:
    {{- include "ovh-dns-updater.labels" . | nindent 4 }}
data:
  domains.yaml: |
    domains:
    {{- range .Values.config.domains }}
      - zone: {{ .zone }}
        records:
        {{- range .records }}
          - {{ . | quote }}
        {{- end }}
    {{- end }}
