{{- if .Values.config.ovhCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovh-dns-updater.fullname" . }}
  labels:
    {{- include "ovh-dns-updater.labels" . | nindent 4 }}
type: Opaque
data:
  OVH_APPLICATION_KEY: {{ .Values.config.ovhCredentials.applicationKey | b64enc }}
  OVH_APPLICATION_SECRET: {{ .Values.config.ovhCredentials.applicationSecret | b64enc }}
  OVH_CONSUMER_KEY: {{ .Values.config.ovhCredentials.consumerKey | b64enc }}
{{- end }}
